apiVersion: v1
kind: Namespace
metadata:
  name: example-namespace

---
apiVersion: v1
kind: Pod
metadata:
  namespace: example-namespace
  name: resource-example
spec:
  containers:
    - name: api-server
      image: hoplin/simple-api
      resources:
        requests:
          cpu: "500m"
          memory: "300Mi"
        limits:
          cpu: "800m"
          memory: "600Mi"
      livenessProbe:
        httpGet:
          path: /health
          port: 3000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
