apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-toleration-test
  labels:
    tier: backend
spec:
  replicas: 6
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx-container
          image: nginx
      tolerations:
        - key: "color"
          operator: "Equal"
          value: "blue"
          effect: "NoSchedule"
