apiVersion: v1
kind: Pod
metadata:
  name: single-toleration-pod
  labels:
    tier: backend
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
    - key: "color"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
