apiVersion: v1
kind: Secret
metadata:
  name: some-secret-3
data:
  COLOR: Z3JlZW4=
  MODE: cHJvZA==

---
apiVersion: v1
kind: Pod
metadata:
  name: some-secret-pod-key-ref
spec:
  containers:
    - name: some-pod
      image: ubuntu
      command: ["/bin/bash", "-c", "echo $MODE_KEY_SHOULD_BE_CHANGED"]
      env:
        - name: MODE_KEY_SHOULD_BE_CHANGED
          valueFrom:
            secretKeyRef:
              name: some-secret-3
              key: MODE
