apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-test
  labels:
    tier: test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: color
                operator: In
                values:
                  - green
                  - blue
  containers:
    - name: nginx-container
      image: nginx
