apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hpa-app
  labels:
    tier: test
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: test
  template:
    metadata:
      labels:
        tier: test
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-hpa-app
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resources:
        name: cpu
        target: Utilization
        averageUtilization: 50
