apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-ns-resoruce-quota
  namespace: test-ns
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "4"
    limits.memory: 5Gi
