apiVersion: v1
kind: Secret
metadata:
  name: some-secret-2
data:
  COLOR: Z3JlZW4=
  MODE: cHJvZA==

---
apiVersion: v1
kind: Pod
metadata:
  name: some-secret-pod
spec:
  containers:
    - name: some-pod
      image: ubuntu
      command: ["/bin/bash", "-c", "printenv"]
      envFrom:
        - secretRef:
            name: some-secret-2
