apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-configs
data:
  COLOR: green
  MODE: prod

---
apiVersion: v1
kind: Pod
metadata:
  name: some-pod
  labels:
    tier: test
spec:
  containers:
    - name: test-container
      image: ubuntu
      command: ["/bin/sh", "-c", "printenv"]
      envFrom:
        - configMapRef:
            name: pod-configs
