apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    tier: test
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: test
  template:
    metadata:
      labels:
        tier: test
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
