apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
    - name: ubuntu
      image: hoplin/ubuntu-curl
      command: ["tail"]
      args: ["-f", "/dev/null"]
