apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-test-deployment
  labels:
    tier: backend
spec:
  replicas: 6
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx-container
          image: nginx
